/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package de.thm.mni.microservices.gruppe6

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }
}
